name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print text
        run: echo "Hello from Workflow 2"