name: workflow 3

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print text from file 
        run: cat dist/index.js